name: {{name}}
description: {{name}} feature

environment: 
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod:
  hooks_riverpod:
  flutter_hooks:

  freezed_annotation:
  json_annotation:

  {{#use_design_system}}
  # design system
  design_system:
    path: ../../core/design_system
  {{/use_design_system}}

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
